name: omr_system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - numpy=1.27.4
  - scipy=1.11.1
  - pillow=10.1.0
  - opencv=4.8.1
  - scikit-learn=1.3.1
  - fastapi=0.111.2
  - uvicorn=0.23.2
  - sqlalchemy=2.0.22
  - psycopg2=2.9.9
  - pip=25.2
  - pip:
      - tensorflow==2.14.0
      - streamlit==1.29.0
      - PyMuPDF==1.22.5
      - pdfplumber==0.11.2
